
ALTER TABLE measurements DROP COLUMN IF EXISTS arm_cm;
ALTER TABLE measurements DROP COLUMN IF EXISTS right_arm_cm;
ALTER TABLE measurements DROP COLUMN IF EXISTS left_arm_cm;
ALTER TABLE measurements DROP COLUMN IF EXISTS thigh_cm;
ALTER TABLE measurements DROP COLUMN IF EXISTS waist_cm;

ALTER TABLE measurements ADD COLUMN IF NOT EXISTS right_biceps_cm  DOUBLE PRECISION;
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS left_biceps_cm   DOUBLE PRECISION;
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS chest_cm         DOUBLE PRECISION;
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS abdomen_cm       DOUBLE PRECISION;
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS hip_cm           DOUBLE PRECISION;
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS right_thigh_cm   DOUBLE PRECISION;
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS left_thigh_cm    DOUBLE PRECISION;
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS right_calf_cm    DOUBLE PRECISION;
ALTER TABLE measurements ADD COLUMN IF NOT EXISTS left_calf_cm     DOUBLE PRECISION;
